#!/usr/bin/env escript
%% -*- erlang -*-
%%! -noshell

-mode(compile).

-define(HEADER, "include/valid_json_metaschema_data.hrl").
-define(SCHEMAS, "priv/json_schema").

main([]) ->
    try
        Project = project_dir(),
        ok = ensure_json(Project),
        Entries = entries(filename:join(Project, ?SCHEMAS)),
        ok = write_if_changed(filename:join(Project, ?HEADER), header(Entries))
    catch
        Class:Reason ->
            io:format(standard_error, "embed_json_schemas: ~p:~p~n",
                      [Class, Reason]),
            halt(1)
    end;
main(Arguments) ->
    io:format(standard_error, "embed_json_schemas: unexpected arguments: ~p~n",
              [Arguments]),
    halt(1).

project_dir() ->
    Script = filename:absname(escript:script_name()),
    filename:dirname(filename:dirname(Script)).

ensure_json(Project) ->
    case code:ensure_loaded(json) of
        {module, json} ->
            ok;
        {error, nofile} ->
            load_vendored_json(Project);
        {error, Reason} ->
            erlang:error({json_module, Reason})
    end.

load_vendored_json(Project) ->
    Directory = filename:join([Project, "vendor", "json"]),
    Source = filename:join(Directory, "json.erl"),
    Options = [binary, return_errors, return_warnings, {i, Directory}],
    case compile:file(Source, Options) of
        {ok, json, Beam} ->
            load_json(Source, Beam);
        {ok, json, Beam, _Warnings} ->
            load_json(Source, Beam);
        {error, Errors, Warnings} ->
            erlang:error({compile_json, Errors, Warnings})
    end.

load_json(Source, Beam) ->
    case code:load_binary(json, Source, Beam) of
        {module, json} -> ok;
        {error, Reason} -> erlang:error({load_json, Reason})
    end.

entries(Root) ->
    Directories = child_directories(Root),
    Files = lists:append([schema_files(Directory) || Directory <- Directories]),
    lists:sort(maps:to_list(lists:foldl(fun add_entry/2, #{}, Files))).

child_directories(Root) ->
    case file:list_dir(Root) of
        {ok, Names} ->
            [filename:join(Root, Name)
             || Name <- lists:sort(Names),
                filelib:is_dir(filename:join(Root, Name))];
        {error, Reason} ->
            erlang:error({list_schema_root, Root, Reason})
    end.

schema_files(Directory) ->
    Root = filename:join(Directory, "schema.json"),
    true = filelib:is_regular(Root),
    [Root | meta_files(filename:join(Directory, "meta"))].

meta_files(Directory) ->
    case file:list_dir(Directory) of
        {ok, Names} ->
            lists:append([meta_entry(filename:join(Directory, Name))
                          || Name <- lists:sort(Names)]);
        {error, enoent} ->
            [];
        {error, Reason} ->
            erlang:error({list_meta, Directory, Reason})
    end.

meta_entry(Path) ->
    case filelib:is_dir(Path) of
        true ->
            meta_files(Path);
        false ->
            case filelib:is_regular(Path) andalso
                 filename:extension(Path) =:= ".json" of
                true  -> [Path];
                false -> []
            end
    end.

add_entry(Path, Entries) ->
    Encoded = read(Path),
    Json = decode(Path, Encoded),
    Uri = document_uri(Path, Json),
    case maps:is_key(Uri, Entries) of
        true  -> erlang:error({duplicate_id, Uri, Path});
        false -> maps:put(Uri, Encoded, Entries)
    end.

read(Path) ->
    case file:read_file(Path) of
        {ok, Encoded} -> Encoded;
        {error, Reason} -> erlang:error({read, Path, Reason})
    end.

decode(Path, Encoded) ->
    try json:decode(Encoded) of
        Json -> Json
    catch
        error:Reason -> erlang:error({invalid_json, Path, Reason})
    end.

document_uri(_Path, #{<<"$id">> := Id}) when is_binary(Id) ->
    without_empty_fragment(Id);
document_uri(Path, _Json) ->
    erlang:error({missing_id, Path}).

%% Draft 6 and 7 spell the empty fragment in `$id`. Registry keys name the
%% document and therefore do not contain a fragment.
without_empty_fragment(Id) ->
    case byte_size(Id) of
        0 -> Id;
        Size ->
            case binary:at(Id, Size - 1) of
                $# -> binary:part(Id, 0, Size - 1);
                _  -> Id
            end
    end.

header(Entries) ->
    Pairs = [io_lib:format("    ~p => ~p", [Uri, Encoded])
             || {Uri, Encoded} <- Entries],
    iolist_to_binary([
        "%% Generated by tools/embed_json_schemas.escript. Do not edit manually.\n",
        "\n",
        "-ifndef(VALID_JSON_METASCHEMA_DATA_HRL).\n",
        "-define(VALID_JSON_METASCHEMA_DATA_HRL, true).\n",
        "\n",
        "-define(VALID_JSON_METASCHEMA_ENTRIES, #{\n",
        join(Pairs, ",\n"), "\n",
        "}).\n",
        "\n",
        "-endif.\n"
    ]).

join([], _Separator) -> [];
join([Item], _Separator) -> Item;
join([Item | Rest], Separator) -> [Item, Separator | join(Rest, Separator)].

write_if_changed(Path, Contents) ->
    case file:read_file(Path) of
        {ok, Contents} ->
            ok;
        {ok, _Old} ->
            file:write_file(Path, Contents);
        {error, enoent} ->
            file:write_file(Path, Contents);
        {error, Reason} ->
            erlang:error({read_generated_header, Path, Reason})
    end.
